Added `water contrib` command!
srujandeshpande/DrinkWaterBot pull request #50
Opened 2021-05-28 16:50 UTC by mukunddeepak

#37: Added the contribute command.
P.S. : Let me know if you need me to make any changes and make another pull request.

2021-05-28 17:40 UTC, srujandeshpande requested changes

2021-05-28 17:40 UTC, srujandeshpande commented on commands/contribute.js
> +    contripy: contripy
Is there any particular reason for the function "contripy"? If not, try changing it to something more descriptive of the command

2021-05-28 17:41 UTC, srujandeshpande commented
Also, 'water help contribute` isn't working that's why I haven't merged it yet. Any idea why?

2021-05-29 03:11 UTC, mukunddeepak commented on commands/contribute.js
> +    contripy: contripy
ok sure ill do that

2021-05-29 03:11 UTC, mukunddeepak commented
Shoot! I forgot to add that. on it!

2021-05-29 03:22 UTC, mukunddeepak commented on commands/contribute.js
> +    contripy: contripy
New pull request on the way!

2021-05-29 03:25 UTC, mukunddeepak commented on commands/contribute.js
> +    contripy: contripy
I have added new commit to same pull request with requested changes!

2021-05-29 03:26 UTC, mukunddeepak commented
I have added new commit to same pull request with requested changes!

2021-05-29 13:59 UTC, merged

2021-05-29 14:01 UTC, srujandeshpande reviewed
Works great, thanks!